#+title: Bad Habit
#+startup: latexpreview
#+roam_alias: "Bad Habit"
#+roam_tags: "General"

* Bad Habit
I have the bad habit to start projects that I never finish.

It's really starting to irk me as some of those projects would be nice to have.


Usually the reason I would suspend work on a project is because I have found
something that interests me more. Maybe another project or some form of
entertainment. The problem is when I am done/have abandoned that I rarely come
back to an unfinished project. It's _old,_ you know? Old and boring. And every
day it seems that something new and exciting comes out.

And I have to try it out.


I can't really see a way of fixing this in the short-term.

And it's not really a priority anyway.
The thing I have the most beef with isn't the fact that I abandon projects,
but that I forget about them. I forget why I needed them, planned features
and sometimes I forget about their existance entirely.


Recently the thing that occupies my attention is [[file:org_roam.org][Org Roam]]
and the publishing system for it.

And so I thought up a thing. I already have all these files here, why not make
one for each project with the relevant info.
It's not exactly some revolutionary idea but it would be nice to have (notice
the implicit creation of a new project).

I could also take notes for project ideas. Stuff that I've thought about
but for some reason or another decided not to try and do.

Without further ado: [[file:projects.org][Projects]]
