#+title: kaltask
#+roam_alias: "kaltask"
#+roam_tags: "Project"
* kaltask
~kaltask~ is a task management system for ~org-mode~.

It's designed to be easily interactable from outside of Emacs via a REST API.

It's purpose is to simplify the tracking and scheduling of tasks.

** Tasks

The system for the tasks themselves is quite simple.

*** Status

- INACTIVE: A task that has not be worked on and
  will not be worked on in the near future
- SCHEDULED: A task that is being considered to be worked on in the near future.
- NEXT: A task that will be worked on in the near future.
  (Usually the day it is marked as such)
- ACTIVE: The task currently being worked on.
  There can only be one ACTIVE task at a time.
  (This restriction is global... i.e it applies to all org files.)

- DONE: A task that is, well, done.
- CANCELLED: A task that is not done but will not be worked on again.
- SUSPENDED: A task that has been worked on but has not been finished yet.

*** Category
:LOGBOOK:
- State "INACTIVE"   from              [2021-03-16 Tue 01:56]
:END:

The task category is decided either by tags of the heading or
the org property ~:CATEGORY:~.

The property overrides the top-level heading if it exists.

*** Other metrics.
:LOGBOOK:
- State "INACTIVE"   from              [2021-03-16 Tue 01:56]
- State "INACTIVE"   from              [2021-03-16 Tue 01:56]
- State "INACTIVE"   from              [2021-03-16 Tue 01:56]
:END:

- Date/time added: useful for statistics. (i.e how much time on average it takes
  to complete a task on average per category and so on)
- Time when status was changed
- Properties of the heading.
- To be expanded if I think of something else.
*** INACTIVE API
:LOGBOOK:
- State "INACTIVE"   from              [2021-03-16 Tue 01:55]
:END:
**** SUSPENDED GET
:LOGBOOK:
- State "SUSPENDED"  from "SCHEDULED"  [2021-03-16 Tue 02:11]
- State "SCHEDULED"  from "INACTIVE"   [2021-03-16 Tue 02:11]
- State "INACTIVE"   from "SCHEDULED"  [2021-03-16 Tue 02:11]
- State "SCHEDULED"  from "NEXT"       [2021-03-16 Tue 02:11]
- State "NEXT"       from "ACTIVE"     [2021-03-16 Tue 02:11]
- State "ACTIVE"     from "DONE"       [2021-03-16 Tue 02:11]
- State "DONE"       from "INACTIVE"   [2021-03-16 Tue 02:11]
- State "INACTIVE"   from              [2021-03-16 Tue 01:55]
:END:
Currently only works for agenda files.
Extend to org-roam/arbitrary org-files
***** DONE /api/tasks
:LOGBOOK:
- State "DONE"       from "CANCELLED"  [2021-03-16 Tue 02:11]
- State "CANCELLED"  from "DONE"       [2021-03-16 Tue 02:11]
- State "DONE"       from "ACTIVE"     [2021-03-16 Tue 02:11]
- State "ACTIVE"     from "NEXT"       [2021-03-16 Tue 02:11]
- State "NEXT"       from "SCHEDULED"  [2021-03-16 Tue 02:10]
- State "SCHEDULED"  from "INACTIVE"   [2021-03-16 Tue 02:10]
- State "INACTIVE"   from              [2021-03-16 Tue 02:10]
:END:

Return all tasks if any.

#+CAPTION: /api/tasks response example
#+ATTR_LATEX: :options frame=single,bgcolor=codeblockbg
#+begin_src json :tangle no
[
    {
        "title": "Throw out trash.",
        "category" : ["Daily", "Chore", "Repeating"],
        "added-time": "2020-09-20 20:31",
        "changelog" : [
            {"from": "INACTIVE", "to": "SCHEDULED",
             "timestamp": "2020-09-20 20:35"},
            {"from": "SCHEDULED", "to": "NEXT",
             "timestamp": "2020-09-21 08:47"},
            {"from": "NEXT", "to": "ACTIVE",
             "timestamp": "2020-09-21 11:40"}
        ],
        "properties" : []
    },
    {
        "title": "Run 'rm -rf /'.",
        "category" : ["Scripts"],
        "added-time": "2020-09-20 19:31",
        "changelog" : [
            {"from": "INACTIVE", "to": "SCHEDULED",
             "timestamp": "2020-09-20 20:35"},
            {"from": "SCHEDULED", "to": "NEXT",
             "timestamp": "2020-09-21 08:47"}
        ],
        "properties" : [ {"name": "ORDERED", "value": "t"} ]
    }
]
#+end_src

***** DONE /api/tasks/active
:LOGBOOK:
- State "DONE"       from "ACTIVE"     [2021-03-16 Tue 02:11]
- State "ACTIVE"     from "NEXT"       [2021-03-16 Tue 02:11]
- State "NEXT"       from "ACTIVE"     [2021-03-16 Tue 02:11]
- State "NEXT"       from "SCHEDULED"  [2021-03-16 Tue 02:11]
- State "SCHEDULED"  from "INACTIVE"   [2021-03-16 Tue 02:11]
- State "INACTIVE"   from              [2021-03-16 Tue 02:11]
:END:

Returns information about the current active task if any.

#+CAPTION: /api/tasks/active response example
#+ATTR_LATEX: :options frame=single,bgcolor=codeblockbg
#+begin_src json :tangle no
{
 "title": "Throw out trash.",
 "category" : ["Daily", "Chore", "Repeating"],
 "timestamp": "2020-09-20 20:31",
 "deadline": "2020-09-21 12:00",
 "scheduled": "2020-09-21 11:30",
 "changelog" : [
     {"from": "INACTIVE", "to": "SCHEDULED",
      "timestamp": "2020-09-20 20:35"},
     {"from": "SCHEDULED", "to": "NEXT",
      "timestamp": "2020-09-21 08:47"},
     {"from": "NEXT", "to": "ACTIVE",
      "timestamp": "2020-09-21 11:40"}
 ],
 "properties" : []
}
#+end_src

***** DONE /api/tasks/scheduled
:LOGBOOK:
- State "DONE"       from              [2021-03-16 Tue 02:11]
:END:

Returns information about the currently scheduled tasks if any.

***** DONE /api/tasks/inactive
:LOGBOOK:
- State "DONE"       from              [2021-03-16 Tue 02:11]
:END:

Returns information about the currently inactive tasks if any.

***** DONE /api/tasks/next
:LOGBOOK:
- State "DONE"       from              [2021-03-16 Tue 02:11]
:END:

Returns information about the next tasks if any.

***** DONE /api/tasks/done
:LOGBOOK:
- State "DONE"       from              [2021-03-16 Tue 02:11]
:END:

Returns information about the done tasks if any.

***** DONE /api/tasks/cancelled
:LOGBOOK:
- State "DONE"       from              [2021-03-16 Tue 02:11]
:END:

Returns information about all cancelled tasks if any.

***** DONE /api/tasks/suspended
:LOGBOOK:
- State "DONE"       from              [2021-03-16 Tue 02:11]
:END:

Returns information about all suspended tasks if any.

**** INACTIVE POST
:LOGBOOK:
- State "INACTIVE"   from              [2021-03-16 Tue 01:55]
:END:
**** INACTIVE PUT
:LOGBOOK:
- State "INACTIVE"   from              [2021-03-16 Tue 01:55]
:END:
**** INACTIVE DELETE
:LOGBOOK:
- State "INACTIVE"   from              [2021-03-16 Tue 01:55]
:END:
